### ISSUE TITLE
Xfluence Skin Bug: Video->File folder extracted thumbnail preview missing

### ISSUE THREAD

**Issue by Mounter81** [Helly1206/skin.xonfluence#25] opened 2018-02-17 08:26 UTC
Hello!
 
I’m using KODI 17.6 with the latest Xfluence skin. It’s the best skin I’ve used so far, but I have runned in a very annyoing bug, which I’ve detected in Video->File View, when enterning a Video folder:
 
Here's a screenshot from the problem: [Link](https://imgur.com/dXKUgmC)
 -> So when I enter a Video folder of a newly downloaded video, there's no extracted preview thumbnail, just the default film rail thumb on the left down corner. Only when I start a video and then exit back to the GUI appears the extracted thumbnail as it should. 

**Log file:**

09:31:01.426 T:18446744071798458656   DEBUG: CDirectoryProvider[]: refreshing..
09:31:01.426 T:18446744071791925536   ERROR: GetDirectory - Error getting
09:31:01.426 T:18446744071798458656   DEBUG: CDirectoryProvider[]: refreshing..
09:31:01.427 T:18446744071791925536   ERROR: GetDirectory - Error getting
09:31:01.427 T:18446744071798458656   DEBUG: CDirectoryProvider[]: refreshing..

11:00:58.759 T:18446744071669020960   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://ipa.ddr.e.ss/Movies4/extrathumbs'
                                            unix_err:'2' error : 'No such file or directory'
11:00:58.759 T:18446744071669020960   ERROR: GetDirectory - Error getting smb://ipa.ddr.e.ss/Movies4/extrathumbs/
11:00:58.763 T:18446744071630952736   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://ipa.ddr.e.ss/Movies4/extrathumbs'
                                            unix_err:'2' error : 'No such file or directory'
11:00:58.764 T:18446744071630952736   ERROR: GetDirectory - Error getting smb://ipa.ddr.e.ss/Movies4/extrathumbs/

10:57:02.107 T:18446744071631997216   ERROR: GetDirectory - Error getting smb://ipa.ddr.e.ss/Movies/extrathumbs/
10:57:02.131 T:18446744071631997216   DEBUG: ffmpeg[842B0920]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
10:57:02.134 T:18446744071633041696   DEBUG: ffmpeg[843AF920]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
10:57:02.308 T:18446744071782197536 WARNING: CPeripheralBusAndroid: ignoring input event for unknown input device with ID 3
10:57:02.311 T:18446744071780108576 WARNING: Previous line repeats 1 times.

09:53:17.426 T:18446744071773575456   ERROR: GetDirectory - Error getting library%3a%2f%2fvideo%2frecentlyaddedmovies.xml%2f/
09:53:17.427 T:18446744071669020960   ERROR: Previous line repeats 2 times.
09:53:17.427 T:18446744071669020960   ERROR: GetDirectory - Error getting
09:53:17.430 T:18446744071773575456   ERROR: Previous line repeats 7 times.
09:53:17.430 T:18446744071773575456   ERROR: GetDirectory - Error getting library%3a%2f%2fvideo%2frecentlyaddedmovies.xml%2f/
 
**Hope you can find the error and make a fix for it maybe.**
 
**Thank you!**

**Comment by Helly1206** [comment] 2018-04-09 07:46
As I already answered in the mail and forum, I am not able to reproduce and solve this issue. Hopefully someone else can help us out. I'll leave it open for a while.

Helly.

**Comment by Helly1206** [comment] 2018-05-11 06:08
Closing as it is not skin related. (see forum for more details).

**Closed by Helly1206** 2018-05-11 06:08 UTC
