### ISSUE TITLE
2 small issues 

### ISSUE THREAD

**Issue by towngeek** [Helly1206/skin.xonfluence#23] opened 2018-01-08 07:15 UTC
im having and issue adding widget from favs and custom allows me to select and kicks it out wont save it   kicks back to the widget window 

as well  when playing music  the fan art  not displaying  

running kodi 17.6
![photo_2018-01-05_23-14-08](https://user-images.githubusercontent.com/34733974/34661754-fcbca43e-f408-11e7-9b18-27e3ed9e9080.jpg)

**Comment by towngeek** [comment] 2018-01-12 06:28
widget window issues be reslove  playing music the fan art not displaying not

**Comment by Helly1206** [comment] 2018-01-15 05:53
?
________________________________
Van: towngeek <notifications@github.com>
Verzonden: vrijdag 12 januari 2018 07:28
Aan: Helly1206/skin.xonfluence
CC: Subscribed
Onderwerp: Re: [Helly1206/skin.xonfluence] 2 small issues (#23)


widget window issues be reslove playing music the fan art not displaying not

**Comment by TheFeliks** [comment] 2018-01-19 18:45
I read this thread 5 times and still can't figured out what's the problem is xD

**Comment by Helly1206** [comment] 2018-04-09 07:47
As I don't understand this issue (and I'm probably not the only-one) and one-one is commenting for a while, I will close it now.

Helly.

**Closed by Helly1206** 2018-04-09 07:47 UTC
